language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer install --dev -n
  - app/console doctrine:schema:create --env=test

script:
  - mkdir -p build/logs
  - phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - php bin/coveralls -v
