<?php

namespace QaSystem\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * @param string $status
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createQueryBuilderForPagination($status)
    {
        $queryBuilder = $this->createQueryBuilder('d')
            ->orderBy('d.id', 'desc');

        if ('all' !== $status) {
            $queryBuilder->andWhere('d.status = :status')
                ->setParameter('status', $status);
        }

        return $queryBuilder;
    }
}
