<?php

namespace QaSystem\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method \QaSystem\CoreBundle\Entity\Project|null findOneById
 */
class ProjectRepository extends EntityRepository
{
}
