<?php

namespace QaSystem\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
    /**
     * @param string $status
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createQueryBuilderForPagination($status)
    {
        $queryBuilder = $this->createQueryBuilder('s')
            ->innerJoin('s.deployments', 'd')
            ->groupBy('s.id')
            ->orderBy('s.name', 'asc');

        if ('all' !== $status) {
            $queryBuilder->andWhere('d.status = :status')
                ->setParameter('status', $status);
        }

        return $queryBuilder;
    }
}
