imports:
    - { resource: config_dev.yml }

parameters:
    tasks_path: "%kernel.root_dir%/../src/QaSystem/CoreBundle/Tests/Fixtures/tasks"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

h4cc_alice_fixtures:
    locale: en_US
    seed: 42
    do_flush: true

    schema_tool: null
    doctrine: orm
