imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

qa_system_core:
  tasks:
    echo:
      name: echo
      command: "echo {{foo}}"
      parameters:
        text:
          name: "Text to print"
          code: text
          type: array
          values:
            - foo
            - world
            - "Hello world"