fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

rocket_jira_cs:
    resource: "@RocketJiraCsBundle/Resources/config/routing.yml"
    prefix:   /

_core:
    resource: "@QaSystemCoreBundle/Resources/config/routing.yml"
