services:
    rocket_jira_cs.project_repository:
        class: Rocket\JiraCsBundle\Document\ProjectRepository
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - Rocket\JiraCsBundle\Document\Project
    rocket_jira_cs.issue_repository:
        class: Rocket\JiraCsBundle\Document\IssueRepository
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - Rocket\JiraCsBundle\Document\Issue

    rocket_jira_cs.sync:
        class: Rocket\JiraCsBundle\Service\Sync
        arguments: ["@rocket_jira_cs.client_factory", "@rocket_jira_cs.project_repository", "@rocket_jira_cs.issue_repository", "@doctrine.odm.mongodb.document_manager"]
    rocket_jira_cs.client_factory:
        class: Rocket\JiraCsBundle\Service\ClientFactory
