<?php

namespace Rocket\JiraCsBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends DocumentRepository
{
}
